version: '3.4'

name: pickiteasy

services:
  pickiteasy.web:
    image: ${DOCKER_REGISTRY-}pickiteasyweb
    container_name: web_combine
    build:
      context: .
      dockerfile: PickItEasy.Web/Dockerfile
    depends_on: 
      - postgres
      - rabbitmq  

  pickiteasy.webapi:
    image: ${DOCKER_REGISTRY-}pickiteasywebapi
    container_name: webapi
    build:
      context: .
      dockerfile: PickItEasy.WebApi/Dockerfile
    depends_on: 
      - postgres
      - rabbitmq

  pickiteasy.webapp.blazorserver:
    image: ${DOCKER_REGISTRY-}pickiteasywebappblazorserver
    container_name: webapp-blazor
    build:
      context: .
      dockerfile: PickItEasy.WebApp.BlazorServer/Dockerfile
    depends_on: 
      - postgres
      - rabbitmq

  postgres:
    image: postgres
    container_name: postgres_container
    ports:
      - "5432:5432"
    volumes:
      - pickiteasy-pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "PickItEasyDb"
      POSTGRES_USER: "PickItEasyUser"
      POSTGRES_PASSWORD: "Pwd4PickItEasy"
      PGDATA: "/var/lib/postgresql/data/pgdata"    

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    ports:
      - "5050:80"
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: "igmo@dobroga.ru"
      PGADMIN_DEFAULT_PASSWORD: "Pwd4PickItEasy"
      PGADMIN_CONFIG_SERVER_MODE: "False"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_container
    ports:
      - "15672:15672"
      - "5672:5672" 
    restart: unless-stopped  

  redis:
    image: redis
    container_name: redis_container
    restart: unless-stopped

  seq:
    image: datalust/seq:latest 
    container_name: seq_container
    hostname: ca2b35a51a38 
    ports:
      - '5341:5341'
      - '81:80' 
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
      - BASE_URI=
      - DATA_DIR=/data

volumes:
  pickiteasy-pgdata:
    name: pickiteasy-pgdata
    driver: local


