version: '3.4'

services:
  pickiteasy.web:
    image: ${DOCKER_REGISTRY-}pickiteasyweb
    container_name: web_combine_container
    environment:
      COMPOSE_PROJECT_NAME: pickiteasy
    build:
      context: .
      dockerfile: PickItEasy.Web/Dockerfile  

  pickiteasy.webapi:
    image: ${DOCKER_REGISTRY-}pickiteasywebapi
    container_name: webapi_container
    environment:
      COMPOSE_PROJECT_NAME: pickiteasy
    build:
      context: .
      dockerfile: PickItEasy.WebApi/Dockerfile

  pickiteasy.webapp.blazorserver:
    image: ${DOCKER_REGISTRY-}pickiteasywebappblazorserver
    container_name: webapp-blazor_container
    environment:
      COMPOSE_PROJECT_NAME: pickiteasy
    build:
      context: .
      dockerfile: PickItEasy.WebApp.BlazorServer/Dockerfile

  postgres:
    container_name: postgres_container
    image: postgres
    command:
      - "postgres"
      - "-c"
      - "max_connections=50"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=4GB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=10GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
    environment:
      POSTGRES_DB: "PickItEasyDb"
      POSTGRES_USER: "PickItEasyUser"
      POSTGRES_PASSWORD: "Pwd4PickItEasy"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .:/docker-entrypoint-initdb.d
      - pickiteasy-pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U PickItEasyUser -d PickItEasyDb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "igmo@dobroga.ru"
      PGADMIN_DEFAULT_PASSWORD: "pwd4pgadmin"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672" 
    restart: unless-stopped

  redis:
    image: redis

volumes:
  pickiteasy-pg-data:
    name: pickiteasy-pg-data
    driver: local

